import { useMemo, useState } from 'react';
import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getSortedRowModel,
  useReactTable,
  type SortingState,
} from '@tanstack/react-table';
import { Input } from './ui/input';
import { Badge } from './ui/badge';
import { Button } from './ui/button';
import { useAppStore } from '../store';
import { rollupSession, formatTokens, computeAiCredits } from '@cue/core';
import { formatDuration, getSessionDisplayTitle } from '@cue/core';
import type { ParsedSession } from '@cue/core';
import { Download, Trash2 } from 'lucide-react';
import { exportSessionListCsv } from '../export';
import { getHost } from '../store';

interface Row {
  session: ParsedSession;
  sessionId: string;
  startedAt: number;
  durationMs: number;
  workspace: string;
  copilotVersion: string;
  turns: number;
  llmCalls: number;
  inputTokens: number;
  outputTokens: number;
  aiCredits: number | null;
  models: string;
  errors: number;
}

export function SessionList() {
  const { sessions, workspaceNames, selectSession, removeSession, redact } = useAppStore();
  const [globalFilter, setGlobalFilter] = useState('');
  const [showNoTurns, setShowNoTurns] = useState(false);
  const [sorting, setSorting] = useState<SortingState>([{ id: 'startedAt', desc: true }]);

  const data = useMemo<Row[]>(() => {
    // Filter out invalid sessions (epoch 0 / before 2020)
    const validSessions = Object.values(sessions).filter(s =>
      s.startedAt > new Date('2020-01-01').getTime()
    );
    return validSessions.map((s) => {
      const r = rollupSession(s);
      const wsName = s.workspaceHash ? workspaceNames[s.workspaceHash] ?? s.workspaceHash : '—';
      return {
        session: s,
        sessionId: s.id,
        startedAt: s.startedAt,
        durationMs: s.durationMs,
        workspace: wsName,
        copilotVersion: s.copilotVersion ?? '—',
        turns: s.turns.length,
        llmCalls: r.llmCalls,
        inputTokens: r.totalInputTokens,
        outputTokens: r.totalOutputTokens,
        aiCredits: computeAiCredits(s),
        models: r.byModel.map((m) => `${m.model}×${m.calls}`).join(', '),
        errors: r.errorCount,
      };
    });
  }, [sessions, workspaceNames]);

  // Sessions with zero turns are utility/background runs (title generation, etc.).
  // Hide them by default; the checkbox reveals them.
  const noTurnCount = useMemo(() => data.filter((r) => r.turns === 0).length, [data]);
  const visibleData = useMemo(
    () => (showNoTurns ? data : data.filter((r) => r.turns > 0)),
    [data, showNoTurns]
  );

  const ch = createColumnHelper<Row>();
  const columns = useMemo(
    () => [
      ch.accessor('sessionId', {
        header: 'Session',
        cell: (i) => {
          const title = getSessionDisplayTitle(i.row.original.session);
          return title ? (
            <div>
              <div className="text-xs font-medium leading-tight">{title}</div>
              <div className="font-mono text-[10px] text-muted-foreground">{i.getValue()}</div>
            </div>
          ) : (
            <span className="font-mono text-xs">{i.getValue()}</span>
          );
        },
      }),
      ch.accessor('startedAt', {
        header: 'Started',
        cell: (i) => new Date(i.getValue()).toLocaleString(),
      }),
      ch.accessor('durationMs', {
        header: 'Duration',
        cell: (i) => formatDuration(i.getValue()),
      }),
      ch.accessor('workspace', { header: 'Workspace' }),
      ch.accessor('copilotVersion', { header: 'Copilot' }),
      ch.accessor('turns', { header: () => <span title="User → assistant exchanges">Turns</span>, cell: (i) => i.getValue().toLocaleString() }),
      ch.accessor('llmCalls', { header: () => <span title="Total model invocations (one turn can trigger many)">LLM calls</span>, cell: (i) => i.getValue().toLocaleString() }),
      ch.accessor('inputTokens', { header: () => <span title="Tokens sent to the model in this session">In tok</span>, cell: (i) => formatTokens(i.getValue()) }),
      ch.accessor('outputTokens', { header: () => <span title="Tokens generated by the model in this session">Out tok</span>, cell: (i) => formatTokens(i.getValue()) }),
      ch.accessor('aiCredits', {
        header: () => <span title="Sum of copilotUsageNanoAiu across llm_request events, when the log includes it">AIC</span>,
        cell: (i) => {
          const v = i.getValue();
          return v === null ? <span className="text-muted-foreground">—</span> : v.toFixed(2);
        },
      }),
      ch.accessor('models', {
        header: 'Models',
        cell: (i) => <span className="text-xs text-muted-foreground">{i.getValue()}</span>,
      }),
      ch.accessor('errors', {
        header: 'Errors',
        cell: (i) =>
          i.getValue() > 0 ? <Badge variant="destructive">{i.getValue()}</Badge> : <span className="text-muted-foreground">0</span>,
      }),
      ch.display({
        id: 'actions',
        header: '',
        cell: (info) => (
          <Button
            size="sm"
            variant="ghost"
            onClick={(e) => {
              e.stopPropagation();
              if (confirm('Remove this session from the local cache?')) removeSession(info.row.original.session.id);
            }}
            aria-label="Remove session"
          >
            <Trash2 className="h-4 w-4" />
          </Button>
        ),
      }),
    ],
    [ch, removeSession]
  );

  const table = useReactTable({
    data: visibleData,
    columns,
    state: { sorting, globalFilter },
    onSortingChange: setSorting,
    onGlobalFilterChange: setGlobalFilter,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    globalFilterFn: 'includesString',
  });

  const exportCsv = () => {
    void getHost().saver.save(
      `cue-sessions-${new Date().toISOString().slice(0, 10)}.csv`,
      exportSessionListCsv(Object.values(sessions), workspaceNames, redact),
      'text/csv;charset=utf-8'
    );
  };
  return (
    <div className="flex h-full flex-col">
      <div className="mb-2 rounded border border-muted bg-muted/30 px-3 py-1.5 text-[11px] text-muted-foreground">
        Each row shows <strong>cumulative totals for one chat session</strong>. Click a row to open the conversation.
      </div>
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <Input
          placeholder="Search across sessions, workspaces, models, errors…"
          value={globalFilter}
          onChange={(e) => setGlobalFilter(e.target.value)}
          className="max-w-md"
        />
        <label
          className="flex cursor-pointer select-none items-center gap-1.5 text-xs text-muted-foreground"
          title="Sessions with no user turns are usually background/utility runs like chat-title generation"
        >
          <input
            type="checkbox"
            className="h-3.5 w-3.5 cursor-pointer accent-primary"
            checked={showNoTurns}
            onChange={(e) => setShowNoTurns(e.target.checked)}
          />
          Show utility sessions
          {noTurnCount > 0 && <span className="text-muted-foreground/70">({noTurnCount} with no turns)</span>}
        </label>
        <div className="ml-auto flex gap-2">
          <Button variant="outline" size="sm" onClick={exportCsv}>
            <Download className="h-4 w-4" />
            Sessions CSV
          </Button>
        </div>
      </div>

      <div className="flex-1 overflow-auto rounded-md border">
        <table className="w-full text-sm">
          <thead className="sticky top-0 bg-muted/60 backdrop-blur">
            {table.getHeaderGroups().map((hg) => (
              <tr key={hg.id}>
                {hg.headers.map((h) => (
                  <th
                    key={h.id}
                    className="cursor-pointer select-none border-b px-2 py-2 text-left text-xs font-medium text-muted-foreground"
                    onClick={h.column.getToggleSortingHandler()}
                  >
                    {flexRender(h.column.columnDef.header, h.getContext())}
                    {h.column.getIsSorted() === 'asc' ? ' ▲' : h.column.getIsSorted() === 'desc' ? ' ▼' : ''}
                  </th>
                ))}
              </tr>
            ))}
          </thead>
          <tbody>
            {table.getRowModel().rows.map((row) => (
              <tr
                key={row.id}
                className="cursor-pointer hover:bg-accent/50"
                onClick={() => selectSession(row.original.session.id)}
              >
                {row.getVisibleCells().map((cell) => (
                  <td key={cell.id} className="border-b px-2 py-2 align-top">
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </td>
                ))}
              </tr>
            ))}
            {table.getRowModel().rows.length === 0 && (
              <tr>
                <td colSpan={columns.length} className="px-4 py-8 text-center text-sm text-muted-foreground">
                  No sessions match.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
